### ISSUE TITLE
Fix comments for Fibonacci example in "Sequences"

### ISSUE THREAD

**Issue by k4y3ff** [cognitect/clojure-lab#27]
When the Fibonacci sequence example from [`sequences.clj`](https://github.com/cognitect/clojure-lab/blob/master/src/cljlab/sequences.clj) is displayed on a projector, the comments on the side sometimes run onto multiple lines, making the code itself very difficult to read.

Move the comments into a descriptive Markdown segment, or something similar.

**Comment by puredanger** [comment]
updated
